name: Simulate Chezmoi Environments

on:
  push:
  pull_request:

jobs:
  simulate-default-linux:
    runs-on: ubuntu-latest
    env:
      CHEZMOI_CONFIG: >
        [data]
          email = "email@gmail.com"
          workemail = ""
          ephemeral = true
          headless = true
          work = false
          personal = false
          gpu = false
          osid = "linux"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Chezmoi Config for Default Environment
        run: |
          mkdir -p home
          echo "$CHEZMOI_CONFIG" > ./home/.chezmoi.toml.tmpl
          echo "Generated Chezmoi config (TOML):"
          cat ./home/.chezmoi.toml.tmpl
      - name: Install Chezmoi
        run: |
          curl -sfL https://git.io/chezmoi | sh
          sudo mv ./bin/chezmoi /usr/local/bin/chezmoi
      - name: Apply Dotfiles Using TOML Config
        run: |
          ls .
          ls home
          cat home/.chezmoi.toml.tmpl
          chezmoi init --help
          chezmoi init --apply --guess-repo-url=false --source .
          chezmoi data

  simulate-work-linux:
    runs-on: ubuntu-latest
    env:
      CHEZMOI_CONFIG: >
        [data]
          email = "email@gmail.com"
          workemail = "email@gmail.com"
          ephemeral = false
          headless = true
          work = true
          personal = true
          gpu = false
          osid = "linux"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Chezmoi Config for Work Environment
        run: |
          mkdir -p home
          echo "$CHEZMOI_CONFIG" > ./home/.chezmoi.toml.tmpl
          echo "Generated Chezmoi config (TOML):"
          cat ./home/.chezmoi.toml.tmpl
      - name: Install Chezmoi
        run: |
          curl -sfL https://git.io/chezmoi | sh
          sudo mv ./bin/chezmoi /usr/local/bin/chezmoi
      - name: Apply Dotfiles Using TOML Config
        run: |
          ls .
          ls home
          cat home/.chezmoi.toml.tmpl
          chezmoi init --help
          chezmoi init --apply --guess-repo-url=false --source .
          chezmoi data

  simulate-gpu-linux:
    runs-on: ubuntu-latest
    env:
      CHEZMOI_CONFIG: >
        [data]
          email = "email@gmail.com"
          workemail = ""
          ephemeral = false
          headless = true
          work = false
          personal = true
          gpu = true
          osid = "linux"
        [data.gpuExtra.corgi]
          gpuHome = "./data/user"
          condaBase = "./data/user/miniconda3"
        [data.gpuExtra.bluejay]
          gpuHome = "./data2/users/user"
          condaBase = "./data2/packages/anaconda3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Chezmoi Config for GPU Environment
        run: |
          mkdir -p home
          echo "$CHEZMOI_CONFIG" > ./home/.chezmoi.toml.tmpl
          echo "Generated Chezmoi config (TOML):"
          cat ./home/.chezmoi.toml.tmpl
      - name: Install Chezmoi
        run: |
          curl -sfL https://git.io/chezmoi | sh
          sudo mv ./bin/chezmoi /usr/local/bin/chezmoi
      - name: Apply Dotfiles Using TOML Config
        run: |
          ls .
          ls home
          cat home/.chezmoi.toml.tmpl
          chezmoi init --help
          chezmoi init --apply --guess-repo-url=false --source .
          chezmoi data
